Repository Dev-Kkoddorong/ClipStory-front, pull requests merged in 2024-05, with the labels that each got.

#15 TC-14#12 : 로그인 페이지 구현 완료#6
  React Project/src/component/Login.css
  React Project/src/component/Login.jsx
Labels: :sparkles: feat

#16 feat: 회원가입 페이지 구현#13
  .vscode/settings.json
  React Project/src/App.js
  React Project/src/component/Login.jsx
  React Project/src/component/MovieComponentList.js
  React Project/src/component/Signup.css
  React Project/src/component/Signup.js
  package-lock.json
Labels: :sparkles: feat

#20 HTML&CSS: 영화 목록 페이지 보완
  React Project/package-lock.json
  React Project/package.json
  React Project/src/App.css
  React Project/src/component/MovieComponentList.css
  React Project/src/component/MovieComponentList.js
  React Project/src/component/bottom.css
  React Project/src/component/bottom.jsx
  React Project/src/component/header.css
  React Project/src/component/header.jsx
  React Project/src/img/Header.png
  React Project/src/img/Logo.png
  React Project/src/img/login_img.png
  React Project/src/img/movierecommend.png
  React Project/src/img/pageleft.png
  React Project/src/img/pageright.png
Labels: 🎨 HTML&CSS

#22 TC-31#21: 회원가입 페이지 api 연동 완료
  React Project/src/component/Signup.js
Labels: :sparkles: feat

#24 TC-32#23: 로그인 페이지 연동 및 추천 서비스 이용시 로그인 필요하도록 로직 수정
  React Project/src/component/Login.js
  React Project/src/component/MovieSelectingPage1.js
  React Project/src/component/MovieSuggestion.js
  React Project/src/component/Signup.js
Labels: :sparkles: feat

#26 Sprint2 마무리
  .vscode/settings.json
  React Project/package-lock.json
  React Project/package.json
  React Project/src/App.css
  React Project/src/App.js
  React Project/src/component/Login.css
  React Project/src/component/Login.js
  React Project/src/component/MovieComponentList.css
  React Project/src/component/MovieComponentList.js
  React Project/src/component/MovieSelectingPage1.js
  React Project/src/component/MovieSuggestion.js
  React Project/src/component/Signup.css
  React Project/src/component/Signup.js
  React Project/src/component/bottom.css
  React Project/src/component/bottom.jsx
  React Project/src/component/header.css
  React Project/src/component/header.jsx
  React Project/src/img/Header.png
  React Project/src/img/Logo.png
  React Project/src/img/login_img.png
  React Project/src/img/movierecommend.png
  React Project/src/img/pageleft.png
  React Project/src/img/pageright.png
  package-lock.json
Labels: :safety_vest: setting

#27 HTML&CSS: 영화 목록 페이지 2차 보완
  React Project/src/App.css
  React Project/src/App.js
  React Project/src/component/LoginPage.css
  React Project/src/component/LoginPage.jsx
  React Project/src/component/MovieComponentList.css
  React Project/src/component/MovieComponentList.js
  React Project/src/component/MovieSelectingPage1.js
  React Project/src/component/Signup.js
  React Project/src/component/SignupPage.css
  React Project/src/component/SignupPage.jsx
  React Project/src/component/bottom.css
  React Project/src/component/bottom.jsx
  React Project/src/component/header.css
  React Project/src/component/header.jsx
  React Project/src/img/Header.png
  React Project/src/img/Header_logo.png
  React Project/src/img/LoginButton.png
  React Project/src/img/header_logo_small.png
  React Project/src/img/login_img.png
  React Project/src/img/signupimg.png
  React Project/src/img/unsplash_akLVnqwvHZ4.png
  React Project/src/index.js
Labels: 🎨 HTML&CSS

#29 HTML&CSS: 추천 페이지 보완#28
  React Project/src/component/MovieSuggestion.js
Labels: 🎨 HTML&CSS

#31 TC-42#30 : 영화 목록 3차 보완
  React Project/src/App.css
  React Project/src/component/MovieComponentList.css
  React Project/src/component/MovieComponentList.js
  React Project/src/component/Signup.js
  React Project/src/component/bottom.css
  React Project/src/component/bottom.jsx
  React Project/src/component/header.css
  React Project/src/component/header.jsx
Labels: :hammer: fix

#35 TC-43#34: 추천페이지 2차 보완
  React Project/src/App.css
  React Project/src/component/MovieSuggestion.css
  React Project/src/component/MovieSuggestion.js
  React Project/src/component/SuggestionHeader.css
  React Project/src/component/SuggestionHeader.js
  React Project/src/component/bottom.css
  React Project/src/img/logo1.png
  React Project/src/img/logo2.png
  React Project/src/img/logo3.png
Labels: 🎨 HTML&CSS

#37 TC-16#36 로딩창 보완
  React Project/src/component/MovieSuggestion.css
  React Project/src/component/MovieSuggestion.js
Labels: :sparkles: feat, 🎨 HTML&CSS

#39 TC-44#38 : K-nn 추천 api 연동
  React Project/src/component/MovieSuggestion.js
Labels: :sparkles: feat

#41 TC-41#40 : 메인 페이지에서 장르별 영화 조회 가능하도록 화면 구성, 연동 완료
  React Project/src/component/MovieComponentList.css
  React Project/src/component/MovieComponentList.js
Labels: :sparkles: feat, 🎨 HTML&CSS

#43 TC-38#42 : 민감한 요소 css 수정
  React Project/src/component/MovieComponentList.css
  React Project/src/component/MovieComponentList.js
  React Project/src/component/MovieSelectPage.css
  React Project/src/component/MovieSelectingPage1.js
  React Project/src/component/MovieSelectingPage2.js
  React Project/src/component/MovieSuggestion.css
  React Project/src/component/MovieSuggestion.js
Labels: :sparkles: feat, 🎨 HTML&CSS

#45 TC-48#44 : 프론트에서 발생하는 버그 통합처리
  React Project/src/component/Login.js
  React Project/src/component/LoginPage.css
  React Project/src/component/LoginPage.jsx
  React Project/src/component/LogoutButton.js
  React Project/src/component/MovieComponentList.js
  React Project/src/component/MovieSelectingPage1.js
  React Project/src/component/MovieSelectingPage2.js
  React Project/src/component/MovieSuggestion.css
  React Project/src/component/MovieSuggestion.js
  React Project/src/component/SignupPage.jsx
  React Project/src/component/header.css
  React Project/src/component/header.jsx
Labels: :hammer: fix

#48 TC-49#47 : 비밀번호 8자리 이상으로 제한
  React Project/src/component/SignupPage.jsx
Labels: :sparkles: feat
