Repository Dev-Kkoddorong/ClipStory-front, pull requests merged in 2024-04, with the labels that each got.

#3 Setting: React 기본 세팅
  React Project/.gitignore
  React Project/README.md
  React Project/package-lock.json
  React Project/package.json
  React Project/public/favicon.ico
  React Project/public/index.html
  React Project/public/logo192.png
  React Project/public/logo512.png
  React Project/public/manifest.json
  React Project/public/robots.txt
  React Project/src/App.css
  React Project/src/App.js
  React Project/src/App.test.js
  React Project/src/index.css
  React Project/src/index.js
  React Project/src/logo.svg
  React Project/src/reportWebVitals.js
  React Project/src/setupTests.js
Labels: :safety_vest: setting

#5 feat: 영화 목록 메인페이지 구현
  React Project/package-lock.json
  React Project/package.json
  React Project/src/App.css
  React Project/src/App.js
  React Project/src/component/MovieComponentList.js
  React Project/src/component/SuggestionPage.js
  React Project/src/reportWebVitals.js
Labels: :sparkles: feat

#8 TC-3#6: localhost에서 연동되게 수정. 영화 목록 전체 조회 페이징으로 연동 완료 #6
  React Project/src/component/MovieComponentList.js
  React Project/src/component/SuggestionPage.js
Labels: :hammer: fix, :sparkles: feat

#9 영화 페이지 구현
  React Project/src/App.css
  React Project/src/App.js
  React Project/src/component/MovieComponentList.js
  React Project/src/component/MovieSelectingPage1.js
  React Project/src/component/MovieSelectingPage2.js
  React Project/src/component/MovieSuggestion.css
  React Project/src/component/MovieSuggestion.js
  React Project/src/component/SuggestionPage.js
Labels: :sparkles: feat

#10 TC-3#6 : localhost에서 연동되게 수정. 영화 추천 페이지 연동 완료#6
  React Project/src/component/MovieComponentList.js
  React Project/src/component/MovieSelectingPage1.js
  React Project/src/component/MovieSelectingPage2.js
  React Project/src/component/MovieSuggestion.js
Labels: :hammer: fix, :sparkles: feat

#11 Sprint1 front 완료
  React Project/.gitignore
  React Project/README.md
  React Project/package-lock.json
  React Project/package.json
  React Project/public/favicon.ico
  React Project/public/index.html
  React Project/public/logo192.png
  React Project/public/logo512.png
  React Project/public/manifest.json
  React Project/public/robots.txt
  React Project/src/App.css
  React Project/src/App.js
  React Project/src/App.test.js
  React Project/src/component/MovieComponentList.js
  React Project/src/component/MovieSelectingPage1.js
  React Project/src/component/MovieSelectingPage2.js
  React Project/src/component/MovieSuggestion.css
  React Project/src/component/MovieSuggestion.js
  React Project/src/index.css
  React Project/src/index.js
  React Project/src/logo.svg
  React Project/src/reportWebVitals.js
  React Project/src/setupTests.js
Labels: :safety_vest: setting
